# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 863fc011d19e9ad114690292e6fd2776fa45cc5e0df624b111b4fc2081ce93a3ab4f69c3c6f1c8227a130741aafe9369463e590e4d32fedcd47eefc9d90a3c9a

test:
  secret_key_base: 409cfb56c0d6b722471adf1b59358988931bef9aede2551cd77463b5e746f5a4ced125a3899669338213e0a5bc3f90b8f61cad2062043ccadcfd6a9e05677934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
